
name: CI

on:
  issues:
    types: [opened, edited, milestoned, demilestoned, closed, reopened]

jobs:
  issue-create:
    runs-on: self-hosted
    steps:
      - name: Issue Create
# 跑项目路径下的index.js
        run: node F:/issue2print/index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
