
name: CI

on:
  issues:
    types: [opened, edited, milestoned, demilestoned, closed, reopened]

jobs:
  issue-create:
    runs-on: self-hosted
    steps:
      - name: Issue Create
        run: node index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
